spring:
  application:
    name: rateLimiter
  data:
    redis:
      host: localhost
      port: 6379
rate-limiter:
  algorithm: FIXED_WINDOW
  limit: 10
  window: 60
  max-tokens: 3
  refill-rate: 1
